# Author: Billy Lieberman <wlieberman@gmail.com>
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: code-dep
  namespace: codercom
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: codeserver
    spec:
      containers:
      - name: code-server
        image: codercom/code-server:3.4.1
        env:
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: coderpassword
                key: password
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 500Mi
        ports:
        - name: http-alt
          containerPort: 8080
        volumeMounts:
          - mountPath: /home/coder/project
            name: code-vol
      securityContext:
        fsGroup: 1000
      volumes:
      - name: code-vol
        persistentVolumeClaim:
            claimName: code-vc
