apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: code-server-ingress
  namespace: codercom
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: code.billylieberman.com
      http:
        paths:
          - path: /
            backend:
              serviceName: code-server-np
              servicePort: 8080
